# See https://www.maturin.rs/config.html

[build-system]
build-backend = "maturin"
requires = ["maturin>=1.0,<2.0", "polars>=1.3.0"]

# Project name must match python package name
# unless `tools.maturin.python-packages` is defined

[project]
name = "bearta-plugin" 
version = "0.1.0"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "polars-talib>=0.1.5",
]

[dependency-groups]
dev = [
    "maturin",
    "pytest",
    "build",
    "polars",
    "pyarrow",
    "ipykernel",
    "invoke",
    "numpy>=2.2.6",
]


[tool.maturin]
python-source = "python"
python-packages = ["bearta"]
module-name = "bearta.plugin"
manifest-path = "bearta_plugin/Cargo.toml"

# When using a custom module name the name must defined with `tool.maturin.module`
# The module name match the rust module name in libs.rs with either
# - the #[pymodule] function definition
# - the the #[pyo3(name = "...")] directive

[tool.pytest.ini_options]
addopts = ["-p no:cacheprovider"]
testpaths = ["tests"]

