"""Generated indicator re-exports; do not edit by hand.

Generated by `scripts/generate-indicator-stubs.py` from each implementation
module's `__all__`. Regenerate with `uv run inv stubs`.
"""

from .alma import ALMA

from .atr import ATR

from .cci import CCI

from .dema import DEMA

from .dmi import DMI

from .ema import EMA

from .hma import HMA

from .kama import KAMA

from .ker import KER

from .linreg import (
    LINREG,
    LINREG_SLOPE,
    LINREG_RVALUE,
    LINREG_RMSE,
)

from .macd import MACD

from .mad import MAD

from .mfi import MFI

from .price import (
    AVGPRICE,
    MEDPRICE,
    TYPPRICE,
    WCLPRICE,
)

from .quadreg import (
    QUADREG,
    QUADREG_CURVE,
    QUADREG_SLOPE,
    QUADREG_RVALUE,
    QUADREG_RMSE,
)

from .rma import RMA

from .rsi import RSI

from .sar import SAR

from .sma import SMA

from .streak import STREAK

from .tema import TEMA

from .trange import TRANGE

from .wma import WMA

from .zlema import ZLEMA

__all__ = [
    "ALMA",
    "ATR",
    "AVGPRICE",
    "CCI",
    "DEMA",
    "DMI",
    "EMA",
    "HMA",
    "KAMA",
    "KER",
    "LINREG",
    "LINREG_RMSE",
    "LINREG_RVALUE",
    "LINREG_SLOPE",
    "MACD",
    "MAD",
    "MEDPRICE",
    "MFI",
    "QUADREG",
    "QUADREG_CURVE",
    "QUADREG_RMSE",
    "QUADREG_RVALUE",
    "QUADREG_SLOPE",
    "RMA",
    "RSI",
    "SAR",
    "SMA",
    "STREAK",
    "TEMA",
    "TRANGE",
    "TYPPRICE",
    "WCLPRICE",
    "WMA",
    "ZLEMA",
]
