"""Type stubs for the compiled `bartons.kernels` extension.

Generated by `scripts/generate-stubs.py` — do not edit by hand.
Regenerate with `just stubs` after adding or changing any `#[pyfunction]`.
"""

import polars as pl
from typing import Literal

__version__: str
__all__: list[str]


def atr(high: pl.Series, low: pl.Series, close: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Average True Range (Wilder's).

    Args:
        high: high prices.
        low: low prices.
        close: close prices.
        period: smoothing period (default 14).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def cci(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Commodity Channel Index.

    Takes the price series to run over, conventionally typical price:
    ``kernels.cci((high + low + close) / 3, period=20)``. The reduction is
    plain Series arithmetic, which polars already vectorizes.

    Args:
        series: input prices.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def ema(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Exponential moving average.

    Args:
        series: input values.
        period: averaging period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def kama(series: pl.Series, *, period: int = 10, fastn: int = 2, slown: int = 30) -> pl.Series:
    """
    Kaufman Adaptive Moving Average.

    An exponential moving average whose smoothing constant is re-derived each
    bar from the efficiency ratio, so it tracks clean trends closely and flattens
    out in chop.

    Args:
        series: input values.
        period: number of changes in the efficiency-ratio window (default 10).
        fastn: period of the fast smoothing bound (default 2).
        slown: period of the slow smoothing bound (default 30).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def ker(series: pl.Series, *, period: int = 10) -> pl.Series:
    """
    Kaufman Efficiency Ratio.

    The net move over a window divided by the total distance travelled within
    it, in 0..=1.

    Args:
        series: input values.
        period: number of changes in the window (default 10).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def linreg(series: pl.Series, period: int = 20, offset: int = 0, rebase_interval: int | None = None, *, output: Literal["forecast", "slope", "rvalue", "rmse"] = 'forecast') -> pl.Series:
    """
    Rolling linear regression statistic.

    Args:
        series: input values.
        period: regression-window length (default 20; minimum 2).
        offset: forecast offset (default 0); nonzero values require output="forecast".
        rebase_interval: maximum bar span for incrementally maintained sums before
            rebasing from the current window. None selects max(1000, 2 * period);
            0 disables rebasing.
        output: statistic to return: "forecast", "slope", "rvalue", or "rmse".

    Returns:
        A Float64 series; null during warmup and after a null resets the window.
    """
    ...


def mad(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Rolling mean absolute deviation.

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def random_prices(n_rows: int = 10000, *, n_chunks: int = 1, n_tickers: int = 1, seed: int = 0, null_first: bool = False) -> pl.DataFrame:
    """
    Generate deterministic OHLCV prices with controlled chunking.

    Args:
        n_rows: number of rows per ticker.
        n_chunks: exact number of chunks in every output column.
        n_tickers: number of price series.
        seed: deterministic pseudo-random seed.
        null_first: whether the first OHLC row of each ticker is null.

    Returns:
        A Polars DataFrame with the requested physical chunk layout.
    """
    ...


def rma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Wilder's running moving average (SMMA / Wilder smoothing).

    Args:
        series: input values.
        period: smoothing period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def rsi(series: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Wilder's Relative Strength Index.

    Args:
        series: input values.
        period: smoothing period (default 14).

    Returns:
        A Float64 series in 0..=100; null during the warmup period.
    """
    ...


def sar(high: pl.Series, low: pl.Series, *, afs: float = 0.02, maxaf: float = 0.2) -> pl.Series:
    """
    Parabolic Stop and Reverse.

    Args:
        high: high prices.
        low: low prices.
        afs: starting acceleration factor (default 0.02).
        maxaf: maximum acceleration factor (default 0.2; zero disables the cap).

    Returns:
        A Float64 series; null until the trend is initialized and on invalid bars.
    """
    ...


def sma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Simple moving average.

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def streak(series: pl.Series) -> pl.Series:
    """
    Count consecutive true values.

    Args:
        series: Boolean input values; false and null reset the count.

    Returns:
        A non-null Int64 series starting at one within each true run and zero
        otherwise.
    """
    ...


def trange(high: pl.Series, low: pl.Series, close: pl.Series) -> pl.Series:
    """
    True Range over high / low / close.

    Args:
        high: high prices.
        low: low prices.
        close: close prices.

    Returns:
        A Float64 series; the first bar uses high - low (no prior close).
    """
    ...


def with_n_chunks(frame: pl.DataFrame, n_chunks: int) -> pl.DataFrame:
    """
    Return a DataFrame with exactly the requested number of physical chunks.

    Args:
        frame: input DataFrame; its existing chunk layout is ignored.
        n_chunks: exact number of chunks in every output column.

    Returns:
        A logically equivalent Polars DataFrame with controlled chunking.
    """
    ...


def wma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Weighted moving average (linearly weighted).

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...
