"""Type stubs for the compiled `bartons.plugin` extension.

Generated by `scripts/generate-stubs.py` — do not edit by hand.
Regenerate with `just stubs` after adding or changing any `#[pyfunction]`.
"""

import polars as pl

__version__: str
__all__: list[str]


def atr(high: pl.Series, low: pl.Series, close: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Average True Range (Wilder's).

    Args:
        high: high prices.
        low: low prices.
        close: close prices.
        period: smoothing period (default 14).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def ema(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Exponential moving average.

    Args:
        series: input values.
        period: averaging period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def rma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Wilder's running moving average (SMMA / Wilder smoothing).

    Args:
        series: input values.
        period: smoothing period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def rsi(series: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Wilder's Relative Strength Index.

    Args:
        series: input values.
        period: smoothing period (default 14).

    Returns:
        A Float64 series in 0..=100; null during the warmup period.
    """
    ...


def sma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Simple moving average.

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def trange(high: pl.Series, low: pl.Series, close: pl.Series) -> pl.Series:
    """
    True Range over high / low / close.

    Args:
        high: high prices.
        low: low prices.
        close: close prices.

    Returns:
        A Float64 series; the first row is null (no prior close).
    """
    ...


def wma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Weighted moving average (linearly weighted).

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...
