"""Type stubs for the compiled `bartons.plugin` extension.

Generated by `scripts/generate-stubs.py` — do not edit by hand.
Regenerate with `just stubs` after adding or changing any `#[pyfunction]`.
"""

import polars as pl

__version__: str
__all__: list[str]


def atr(high: pl.Series, low: pl.Series, close: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Average True Range (Wilder's).

    Args:
        high: high prices.
        low: low prices.
        close: close prices.
        period: smoothing period (default 14).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def ema(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Exponential moving average.

    Args:
        series: input values.
        period: averaging period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def random_prices(n_rows: int = 10000, *, n_chunks: int = 1, n_tickers: int = 1, seed: int = 0, null_first: bool = False) -> pl.DataFrame:
    """
    Generate deterministic OHLCV prices with controlled chunking.

    Args:
        n_rows: number of rows per ticker.
        n_chunks: exact number of chunks in every output column.
        n_tickers: number of price series.
        seed: deterministic pseudo-random seed.
        null_first: whether the first OHLC row of each ticker is null.

    Returns:
        A Polars DataFrame with the requested physical chunk layout.
    """
    ...


def rma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Wilder's running moving average (SMMA / Wilder smoothing).

    Args:
        series: input values.
        period: smoothing period (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def rsi(series: pl.Series, *, period: int = 14) -> pl.Series:
    """
    Wilder's Relative Strength Index.

    Args:
        series: input values.
        period: smoothing period (default 14).

    Returns:
        A Float64 series in 0..=100; null during the warmup period.
    """
    ...


def sma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Simple moving average.

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...


def trange(high: pl.Series, low: pl.Series, close: pl.Series) -> pl.Series:
    """
    True Range over high / low / close.

    Args:
        high: high prices.
        low: low prices.
        close: close prices.

    Returns:
        A Float64 series; the first row is null (no prior close).
    """
    ...


def with_n_chunks(frame: pl.DataFrame, n_chunks: int) -> pl.DataFrame:
    """
    Return a DataFrame with exactly the requested number of physical chunks.

    Args:
        frame: input DataFrame; its existing chunk layout is ignored.
        n_chunks: exact number of chunks in every output column.

    Returns:
        A logically equivalent Polars DataFrame with controlled chunking.
    """
    ...


def wma(series: pl.Series, *, period: int = 20) -> pl.Series:
    """
    Weighted moving average (linearly weighted).

    Args:
        series: input values.
        period: window length (default 20).

    Returns:
        A Float64 series; null during the warmup period.
    """
    ...
