"""Generate `python/bartons/kernels.pyi` from the compiled extension.

The kernels module is a compiled `.so`, so type checkers cannot see into it —
`ty` reports `Module bartons has no member kernels` for every import. A stub fixes
that, and this script derives it from the module itself rather than a
hand-maintained copy that can drift.

pyo3 exposes parameter names, keyword-only markers, defaults and docstrings at
runtime (from `#[pyo3(signature = ...)]` and the `///` comments), but **no type
information** — `__annotations__` is absent. Types therefore come from
`PARAM_TYPES` below, which is small because the whole surface uses five
parameter names. An unknown name is a hard error rather than a silent `Any`, so
adding a differently-named parameter forces a deliberate choice here.

(pyo3-stub-gen, the Rust-side generator, cannot be used: every signature is in
terms of pyo3-polars' `PySeries`, which does not implement its `PyStubType`, and
the orphan rule prevents supplying that impl. See BACKLOG/CHANGELOG.)

Run via `just stubs`, which builds first so the introspected module is current.
"""

import inspect
import subprocess
from pathlib import Path

from bartons import kernels

# pyo3 carries no type info; supply it here. Keyed by parameter name because the
# surface is uniform — every price series is a Series, every period an int.
PARAM_TYPES = {
    "series": "pl.Series",
    "src": "pl.Series",
    "high": "pl.Series",
    "low": "pl.Series",
    "close": "pl.Series",
    "volume": "pl.Series",
    "period": "int",
    "offset": "int",
    "rebase_interval": "int | None",
    "fastn": "int",
    "slown": "int",
    "afs": "float",
    "maxaf": "float",
    "n_rows": "int",
    "n_chunks": "int",
    "n_tickers": "int",
    "seed": "int",
    "null_first": "bool",
    "frame": "pl.DataFrame",
}
OUTPUT_TYPES = {
    "linreg": 'Literal["forecast", "slope", "rvalue", "rmse"]',
    "quadreg": 'Literal["forecast", "curve", "slope", "rvalue", "rmse"]',
}
RETURN_TYPES = {
    "random_prices": "pl.DataFrame",
    "with_n_chunks": "pl.DataFrame",
}

OUT = Path(__file__).resolve().parent.parent / "python" / "bartons" / "kernels.pyi"

HEADER = '''"""Type stubs for the compiled `bartons.kernels` extension.

Generated by `scripts/generate-stubs.py` — do not edit by hand.
Regenerate with `just stubs` after adding or changing any `#[pyfunction]`.
"""

import polars as pl
from typing import Literal

__version__: str
__all__: list[str]
'''


def annotate(function_name: str, param: inspect.Parameter) -> str:
    type_ = OUTPUT_TYPES.get(function_name) if param.name == "output" else None
    if type_ is None:
        type_ = PARAM_TYPES.get(param.name)
    if type_ is None:
        raise SystemExit(
            f"generate-stubs: no type mapped for parameter {param.name!r}. "
            f"Add it to PARAM_TYPES in {Path(__file__).name}."
        )
    rendered = f"{param.name}: {type_}"
    if param.default is not inspect.Parameter.empty:
        rendered += f" = {param.default!r}"
    return rendered


def render(name: str, func) -> str:
    params, seen_kwonly = [], False
    for param in inspect.signature(func).parameters.values():
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not seen_kwonly:
            params.append("*")
            seen_kwonly = True
        params.append(annotate(name, param))

    return_type = RETURN_TYPES.get(name, "pl.Series")
    lines = [f"def {name}({', '.join(params)}) -> {return_type}:"]
    doc = inspect.getdoc(func)
    if doc:
        lines.append('    """')
        lines.extend(f"    {line}".rstrip() for line in doc.splitlines())
        lines.append('    """')
    lines.append("    ...")
    return "\n".join(lines)


def main() -> None:
    functions = sorted(
        (name, obj)
        for name in dir(kernels)
        if inspect.isbuiltin(obj := getattr(kernels, name))
    )
    if not functions:
        raise SystemExit("generate-stubs: no pyfunctions found — is the extension built?")

    body = "\n\n\n".join(render(name, func) for name, func in functions)
    OUT.write_text(f"{HEADER}\n\n{body}\n")
    print(f"wrote {OUT.relative_to(Path.cwd())} ({len(functions)} functions)")

    # The stub must describe what is actually exported, both ways.
    exported = {n for n in getattr(kernels, "__all__", []) if not n.startswith("__")}
    stubbed = {name for name, _ in functions}
    if exported != stubbed:
        raise SystemExit(
            f"generate-stubs: __all__ and the stubbed functions disagree — "
            f"only in __all__: {exported - stubbed}, only stubbed: {stubbed - exported}"
        )


if __name__ == "__main__":
    main()
