"""Generate `python/bartons/kernels.pyi` from the compiled extension.

PyO3 exposes signatures and docstrings but no annotations, so types come from
the maps below. Unknown parameters fail generation rather than default to Any.

Run via `uv run inv stubs`, which builds first so the introspected module is current.
"""

import inspect
from pathlib import Path

from bartons import kernels

PARAM_TYPES = {
    "series": "pl.Series",
    "src": "pl.Series",
    "high": "pl.Series",
    "low": "pl.Series",
    "close": "pl.Series",
    "volume": "pl.Series",
    "period": "int",
    "offset": "int",
    "sigma": "float",
    "rebase_interval": "int | None",
    "fastn": "int",
    "slown": "int",
    "afs": "float",
    "maxaf": "float",
    "multiplier": "float",
    "threshold": "float",
    "n_rows": "int",
    "n_chunks": "int",
    "n_tickers": "int",
    "seed": "int",
    "null_first": "bool",
    "frame": "pl.DataFrame",
}
PARAM_OVERRIDES = {
    ("alma", "offset"): "float",
    ("linreg", "output"): 'Literal["forecast", "slope", "rvalue", "rmse"]',
    ("quadreg", "output"): 'Literal["forecast", "curve", "slope", "rvalue", "rmse"]',
}
RETURN_TYPES = {
    "random_prices": "pl.DataFrame",
    "with_n_chunks": "pl.DataFrame",
}

OUT = Path(__file__).resolve().parent.parent / "python" / "bartons" / "kernels.pyi"

HEADER = '''"""Type stubs for the compiled `bartons.kernels` extension.

Generated by `scripts/generate-kernel-stubs.py` — do not edit by hand.
Regenerate with `uv run inv stubs` after adding or changing any `#[pyfunction]`.
"""

import polars as pl
from typing import Literal

__version__: str
__all__: list[str]
'''


def annotate(function_name: str, param: inspect.Parameter) -> str:
    type_ = PARAM_OVERRIDES.get(
        (function_name, param.name), PARAM_TYPES.get(param.name)
    )
    if type_ is None:
        raise SystemExit(
            f"generate-kernel-stubs: no type mapped for parameter {param.name!r}. "
            f"Add it to PARAM_TYPES in {Path(__file__).name}."
        )
    rendered = f"{param.name}: {type_}"
    if param.default is not inspect.Parameter.empty:
        rendered += f" = {param.default!r}"
    return rendered


def render(name: str, func) -> str:
    params, seen_kwonly = [], False
    for param in inspect.signature(func).parameters.values():
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not seen_kwonly:
            params.append("*")
            seen_kwonly = True
        params.append(annotate(name, param))

    return_type = RETURN_TYPES.get(name, "pl.Series")
    lines = [f"def {name}({', '.join(params)}) -> {return_type}:"]
    doc = inspect.getdoc(func)
    if doc:
        lines.append('    """')
        lines.extend(f"    {line}".rstrip() for line in doc.splitlines())
        lines.append('    """')
    lines.append("    ...")
    return "\n".join(lines)


def main() -> None:
    functions = inspect.getmembers(kernels, inspect.isbuiltin)
    if not functions:
        raise SystemExit("generate-kernel-stubs: no pyfunctions found — is the extension built?")

    # The stub must describe what is actually exported, both ways.
    exported = {n for n in getattr(kernels, "__all__", []) if not n.startswith("__")}
    stubbed = {name for name, _ in functions}
    if exported != stubbed:
        raise SystemExit(
            f"generate-kernel-stubs: __all__ and the stubbed functions disagree — "
            f"only in __all__: {exported - stubbed}, only stubbed: {stubbed - exported}"
        )

    body = "\n\n\n".join(render(name, func) for name, func in functions)
    OUT.write_text(f"{HEADER}\n\n{body}\n")
    print(f"wrote {OUT.relative_to(Path.cwd())} ({len(functions)} functions)")


if __name__ == "__main__":
    main()
