"""Generate typed re-exports for the dynamic indicator package surface."""

from indicator_exports import PACKAGE, indicator_exports


OUT = PACKAGE / "__init__.pyi"
HEADER = '''"""Generated indicator re-exports; do not edit by hand.

Generated by `scripts/generate-indicator-stubs.py` from each implementation
module's `__all__`. Regenerate with `just stubs`.
"""
'''


def render_module(module: str, names: tuple[str, ...]) -> str:
    if len(names) == 1:
        name = names[0]
        return f"from .{module} import {name}"

    members = "\n".join(f"    {name}," for name in names)
    return f"from .{module} import (\n{members}\n)"


def main() -> None:
    exports = indicator_exports()
    names = [name for _, module_names in exports for name in module_names]
    duplicates = {name for name in names if names.count(name) > 1}
    if duplicates:
        raise SystemExit(
            f"generate-indicator-stubs: duplicate exports: {sorted(duplicates)}"
        )

    body = "\n\n".join(render_module(module, names) for module, names in exports)
    public = "\n".join(f'    "{name}",' for name in sorted(names))
    OUT.write_text(f"{HEADER.rstrip()}\n\n{body}\n\n__all__ = [\n{public}\n]\n")
    print(f"wrote {OUT.relative_to(PACKAGE.parents[2])} ({len(names)} exports)")


if __name__ == "__main__":
    main()
